# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NearestPointDistance
                                 A QGIS plugin
 This plugin exports Nearest Point & distance.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-02-14
        copyright            : (C) 2021 by Ginnannman
        email                : ginnannman@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Ginnannman'
__date__ = '2021-02-14'
__copyright__ = '(C) 2021 by Ginnannman'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NearestPointDistance class from file NearestPointDistance.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Nearest_Point_Distance import NearestPointDistancePlugin
    return NearestPointDistancePlugin()
